FROM node:20-alpine AS builder

WORKDIR /app

COPY --chown=node:node package*.json ./

RUN npm ci 

COPY --chown=node:node . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]